FROM golang:1.23-alpine AS build
WORKDIR /notify

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/notify

FROM alpine:3.20 AS run

COPY --from=build /notify/main /main

EXPOSE 8080
ENTRYPOINT ["/main"]